# cAdvisor service added to an existing compose stack
services:
  monitoring:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: notes-monitor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
